version: '3.7'
services:
    database:
        container_name: database
        image: mongo
        command: [--auth]
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: 123456
            TZ: Asia/Shanghai
        volumes:
            - ~/data/db:/data/db
        networks:
            - blog
        ports:
            - 27017:27017
    service:
        build: ./blog-service
        container_name: service
        image: service
        depends_on:
            - database
        ports:
            - 3000:3000
        networks:
            - blog
    front:
        build: ./blog-front
        container_name: front
        image: front
        depends_on:
            - database
        ports:
            - 8000:8000
        networks:
            - blog
    nginx:
        container_name: nginx
        image: nginx
        ports:
            - 80:80
        volumes:
            - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - /etc/nginx/conf.d:/etc/nginx/conf.d
            - /etc/nginx/mime.types:/etc/nginx/mime.types
        restart: always
        depends_on:
            - service
        networks:
            - blog
networks:
    blog:
        driver: bridge
